spring.application.name=SpringSecurity

# R2DBC Supabase (Transaction Pooler)
spring.r2dbc.url=r2dbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslMode=require
spring.r2dbc.username=postgres.isguycvywkkrydclduie
spring.r2dbc.password=Doomguy_611

# Inicialización SQL (si usas schema.sql o data.sql)
spring.sql.init.mode=always

# Logs útiles para depuración de conexión
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG